// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evalaution;

namespace evalaution.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20200914175721_Test")]
    partial class Test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain_Modules.objects.DailyIncome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AmountMade")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<int>("CompulsorySavings")
                        .HasColumnType("int");

                    b.Property<int>("PercentageProfit")
                        .HasColumnType("int");

                    b.Property<int>("Profit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyIncomes");
                });

            modelBuilder.Entity("Domain_Modules.objects.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid>("DailyIncomeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DailyIncomeId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DailyIncomeId");

                    b.HasIndex("DailyIncomeId1");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Domain_Modules.objects.Expense", b =>
                {
                    b.HasOne("Domain_Modules.objects.DailyIncome", "DailyIncome")
                        .WithMany()
                        .HasForeignKey("DailyIncomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain_Modules.objects.DailyIncome", null)
                        .WithMany("Expenses")
                        .HasForeignKey("DailyIncomeId1");
                });
#pragma warning restore 612, 618
        }
    }
}
